server:
  port: 8090
spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 30
    eviction-interval-timer-in-ms: 60000
    peer-node-connect-timeout-ms: 600000
    peer-node-read-timeout-ms: 600000

