server:
  port: 8093
spring:
  application:
    name: auth
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123
    url: jdbc:postgresql://localhost:5432/esme
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework:
        security: DEBUG

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
