server:
  port: 8092
spring:
  application:
    name: gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: expenses
          uri: http://expenses
          predicates:
            - Path=/expenses/**
          filters:
            - StripPrefix=1
        - id: calender
          uri: http://calender
          predicates:
            - Path=/calender/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8090/eureka/